### ISSUE TITLE
[meta] Python3 vs Python2

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/bc#107]
**DISCLAIMER**: I don't want to start a flame war.

**Related with:** #71 and #105.

I know that lots of Python packages are incompatible with Python3 and maybe never will be but lots of them already are (e.g. Numpy, Scipy, matplotlib, IPython, ...).

What about the Python lessons start using only Python3 print syntax?
## Short version of why using Python3 print syntax

``` shell
$ python2
Python 2.7.5 (default, Sep  6 2013, 09:55:21) 
[GCC 4.8.1 20130725 (prerelease)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> print 'foo'
foo
>>> print('foo')
foo
>>> quit()
$ python3
Python 3.3.2 (default, Sep  6 2013, 09:30:10) 
[GCC 4.8.1 20130725 (prerelease)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> print 'foo'
  File "<stdin>", line 1
    print 'foo'
              ^
SyntaxError: invalid syntax
>>> print('foo')
foo
>>> quit()
```
## Long version of why using Python3 print syntax

Since Software Carpentry are teaching scientists how to better programming I think that keep using features that will be deprecated in "short" time instead of another that are back compatible isn't the way to show how to improve your programming skills.

**Comment by takluyver** [comment]
To inform this, in a [recent workshop](http://bids.github.io/2015-06-04-berkeley/) at Berkeley, we tried converting the Python parts of the course to Python 3 and teaching with that. It all basically went smoothly. A couple of people showed up with Python 2 installed despite the instructions, but they could follow along OK. I've noticed in recent workshops that some people show up with Python 3 when the course is using Python 2, and they usually have more problems than our Python 2 users did.

This was with a more intermediate group, I hope to try the experiment for a beginner level course as well.

We even managed to work the differences between Python versions into the testing session; @katyhuff got them to push tests to Github and set up Travis CI (which is pretty amazing, I don't think I've ever seen a workshop get that far before). They could then see the tests fail on Python 2 because of integer division, push a fix and watch them pass.

**Comment by takluyver** [comment]
(my comment seems to have unassigned @ahmadia - Github bug?)

**Comment by r-gaia-cs** [comment]
> To inform this, in a recent workshop at Berkeley, we tried converting the Python parts of the course to Python 3 and teaching with that.

Thanks. We are now keeping the Python lesson at https://github.com/swcarpentry/python-novice-inflammation/. And I think that this year we are finally porting the lesson to Python3.

> (my comment seems to have unassigned @ahmadia - Github bug?)

I don't see how.

**Comment by Juanlu001** [comment]
According to Microsoft, [Python 3 is winning](https://blogs.msdn.microsoft.com/pythonengineering/2016/03/08/python-3-is-winning/). [As the end of Python 2 approaches](http://pythonclock.org/), more projects are making plans to drop Python 2 support in 2020 or earlier [and encouraging users to switch](http://python3statement.github.io/). I'm sure all or almost all of you are already aware of these efforts, but just wanted to drop some links here one year after the last comment :)
